IBX-57: Exclusion category features
ezsystems/user-documentation pull request #114
Opened 2021-11-24 10:25 UTC by juskora

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | https://issues.ibexa.co/browse/IBX-57
| Versions      | 4.0

2021-11-24 12:20 UTC, kaborkowski approved these changes

2021-11-24 12:20 UTC, kaborkowski commented on docs/personalization/filters.md
> +With Exclusion features you can exclude categories from the recommendation response by providing fixed category paths or by item category paths.
Maybe could be `or by context item category paths`?

2021-11-24 12:20 UTC, kaborkowski commented on docs/personalization/filters.md
> +- Exclude category of the context item - excludes items in the recommendation response from specified categories in the recommendation request. Select this checkbox if you want do not want to recomme
I think that it coulde be something like:  `excludes items in the recommendation response from the same categories as context item`
too many: 'want'

2021-11-25 12:35 UTC, juskora commented
@dkorostynski could you review?

2021-11-30 09:42 UTC, dkorostynski approved these changes

2021-11-30 09:44 UTC, kaborkowski approved these changes

2021-11-30 09:59 UTC, DominikaK requested changes

2021-11-30 09:59 UTC, DominikaK commented on docs/personalization/filters.md
> +With Exclusion features you can exclude categories from the recommendation response by providing fixed category paths or by context item category paths.
How about:
```suggestion
You can exclude categories from the recommendation response by providing fixed category paths or by context item category paths.
```
Unless the name "Exclusion" is important to retain?

2021-11-30 09:59 UTC, DominikaK commented on docs/personalization/filters.md
> +    You can use both options at the same time.
```suggestion
    You can use both fixed category and context item category paths at the same time.
```

2021-11-30 09:59 UTC, DominikaK commented on docs/personalization/filters.md
> +- Exclude category of the context item - excludes items in the recommendation response from the same categories as the context item in the recommendation request. Select this checkbox if you want do
```suggestion
- Exclude category of the context item - excludes items in the recommendation response from the same categories as the context item in the recommendation request.
Select this checkbox if you do not want to recommend items from the category of the currently rendered item. For example, 
```

2021-11-30 09:59 UTC, DominikaK commented on docs/personalization/filters.md
> +if customer browses items from category *TV*, you can set that other recommendation box or boxes will not display recommendations from this category. This is automatically defined from the context.
```suggestion
if the customer is browsing items from the *TV* category, you can ensure that recommendation boxes do not display recommendations from this category. This is automatically defined from the context.
```

2021-11-30 09:59 UTC, DominikaK commented on docs/personalization/filters.md
> +- Exclude category of the context item - excludes items in the recommendation response from the same categories as the context item in the recommendation request. Select this checkbox if you want do
or
```suggestion
- **Exclude category of the context item** - excludes items in the recommendation response from the same categories as the context item in the recommendation request.
Select this checkbox if you do not want to recommend items from the category of the currently rendered item. For example, 
```
if it is a label in the UI

2021-11-30 09:59 UTC, DominikaK commented on docs/personalization/filters.md
> +- Exclude category - use to define lists of categories which should not be recommended in a scenario. Excludes the category that is last in the path. For example, in the following category path: *Fur
```suggestion
- **Exclude category** - define lists of categories which should not be recommended in a scenario.
Excludes the category that is last in the path.
For example, in the following category path: *Furniture/Living room/Sofas*, for this scenario all items from the *Sofas* category are excluded. You can add many categories.
```

2021-11-30 09:59 UTC, DominikaK commented on docs/personalization/scenarios.md
> +Filters are applied to all recommendations come from models selected in the strategy.
```suggestion
Filters are applied to all recommendations that come from models selected in the strategy.
```

2021-11-30 09:59 UTC, DominikaK commented on docs/personalization/scenarios.md
> +If you want to configure category filters for each of the categories from the strategy configuration matrix, click the **Configure** icon and make necessary changes.
```suggestion
If you want to configure category filters for each of the categories from the strategy configuration matrix,
click the **Configure** icon and make necessary changes.
```

2021-11-30 11:03 UTC, merged