Ibx 23 taxonomy
ezsystems/user-documentation pull request #121
Opened 2022-03-11 14:04 UTC by juskora

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | https://issues.ibexa.co/browse/IBX-23
| Versions      | master, 4.0

2022-03-14 10:27 UTC, webhdx commented on docs/taxonomy.md
> +In the site tree in the left pane, you can create a hierarchy of all tags and navigate in the platform.
`pane` typo?

2022-03-14 10:27 UTC, webhdx commented on docs/taxonomy.md
> +You can assign tags in three ways.
There is only one way to assign tags to Content - via content create/edit form.

2022-03-14 10:27 UTC, webhdx commented on docs/taxonomy.md
> +Open Content Type, scroll down, in the section Select tags, you can add tag by typing or click **Select from tree**.
Open Content item? Or better edit/create content item?

2022-03-25 13:53 UTC, webhdx approved these changes

2022-03-25 14:16 UTC, DominikaK requested changes

2022-03-25 14:16 UTC, DominikaK commented on docs/creating_content_basic.md
> +To keep your content organized and easy to find, you can add taxonomy entries to a content while creating or editing it.
```suggestion
To keep your content organized and easy to find, you can add taxonomy entries to a Content item while creating or editing it.
```

2022-03-25 14:16 UTC, DominikaK commented on docs/taxonomy.md
> +1. Click the respective tag and go to the **Translations** tab.
```suggestion
1. Click a tag and go to the **Translations** tab.
```

2022-03-28 11:40 UTC, DominikaK approved these changes

2022-03-28 11:46 UTC, merged