IBX-2889: Cross content type recommendations
ezsystems/user-documentation pull request #141
Opened 2022-08-01 10:48 UTC by juskora

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | https://issues.ibexa.co/browse/IBX-2889
| Versions      | 4.2, master

Steps for Dynamic targeting block will be updates as soon as the option with output type is added.

2022-08-18 06:23 UTC, ciastektk approved these changes

2022-08-18 06:23 UTC, ciastektk commented on docs/personalization/cross_content_type_reco.md
> +Cross content type option is used to get multiple recommendation items for each input types.
```suggestion
Cross content type option is used to get multiple recommendation items for each output types. 
```

2022-08-22 12:37 UTC, dabrt requested changes

2022-08-22 12:37 UTC, dabrt commented on docs/personalization/cross_content_type_reco.md
> +The **All** option automatically appears after content types are selected in the scenario settings.
It seems that if one has selected several output types in the edit phase, the "All" option is selected by default when you go to. preview, so there is no need to select it. You could say something like...

``` suggestion
1. From the **Output type** drop-down, select the outputs for which you want to generate the preview. 
```

And then, the sentence about the "All" option makes more sense:

"After you select content types in the scenario settings, the **All** option automatically appears here and, by default, it is selected."

However, on a second thought, it is describing the inner workings of the system, so why not simply:

"By default, the **All** option is selected."

2022-08-22 12:37 UTC, dabrt commented on docs/personalization/cross_content_type_reco.md
> +When scenarios are configured to display cross content type recommendations, you can use them in the two Page Builder blocks: Dynamic targeting and Personalized.
```suggestion
When scenarios are configured to display cross content type recommendations, you can use them in the following Page Builder blocks: Dynamic targeting and Personalized.
```

2022-08-22 12:37 UTC, dabrt commented on docs/personalization/cross_content_type_reco.md
> +To get all output types in the [Personalized block](../site_organization/working_with_page.md#personalized-block), in the Page Builder mode perform the following:
```suggestion
To get all output types in the [Personalized block](../site_organization/working_with_page.md#personalized-block), in Page Builder, perform the following actions:
```

2022-08-22 12:37 UTC, dabrt commented on docs/personalization/cross_content_type_reco.md
> +1. Click **Submit**.
```suggestion
1. Click the **Edit** icon to display the settings of the **Personalized** block.
1. Select a scenario with cross content types output configured.
1. From the **Select a Content Type to be displayed** drop-down, select **All**.
1. Increase the display limit to ensure that all recommendations are shown.
1. Click **Submit**.
```

2022-08-22 12:37 UTC, dabrt commented on docs/personalization/cross_content_type_reco.md
> +1. Click **Submit**.
```suggestion
1. Click the **Edit** icon to display the settings of the **Dynamic targeting** block.
1. Select a scenario with cross content types output configured.
1. From the **Output type** drop-down, select **All**.
1. Set the matching rules according to your needs.
1. Click **Submit**.
```

2022-08-22 12:37 UTC, dabrt commented on docs/personalization/scenarios.md
> +Every recommendation request can deliver content of one or all output content types.
How about selecting two out of three available content types? If this is doable, I'd go with: 

```suggestion
Every recommendation request can deliver content of one or more output content types.
```

2022-08-22 12:37 UTC, dabrt commented on docs/site_organization/working_with_page.md
> +- **Display limit** – Set the number of products to be displayed, for example, 4.
```suggestion
- In the **Display limit** field, set the number of recommended items to be displayed, for example, 4.
```

2022-08-22 13:47 UTC, dabrt approved these changes

2022-08-23 08:47 UTC, merged