IBX-4091: Added predictive and recurring purchase models
ezsystems/user-documentation pull request #177
Opened 2023-01-05 07:55 UTC by juskora

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | https://issues.ibexa.co/browse/IBX-4091 https://issues.ibexa.co/browse/IBX-4071
| Versions      | 4.4, master

Scope:
Covers descriptions for both Predictive and recurring purchase models.

#### Checklist

- [ ] Text renders correctly
- [ ] Text has been checked with vale
- [ ] Description metadata is up to date
- [ ] Redirects cover removed/moved pages
- [ ] Added link to this PR in relevant JIRA ticket or code PR

2023-01-09 08:39 UTC, mnitek-ibexa commented on docs/personalization/recommendation_models.md
> +Predicts user's purchase behavior and trends, and recommends items based on this behavior.
users'
In case of predictive model, all purchases or clicks of particular item are taken into account

2023-01-16 09:11 UTC, mnitek-ibexa approved these changes

2023-01-16 10:38 UTC, DominikaK requested changes

2023-01-16 10:38 UTC, DominikaK commented on docs/personalization/recommendation_models.md
> +Predicts users' purchase behavior and trends, and recommends items based on this behavior.
```suggestion
A predictive popularity model predicts users' purchase behavior and trends, and recommends items based on this behavior.
```

2023-01-16 10:38 UTC, DominikaK commented on docs/personalization/recommendation_models.md
> +The model analyzes trends within a configured time period (for example, within a 30-day timeframe), and predicts that a new item may have the same trend, and displays the predicted item in recommenda
```suggestion
The model analyzes trends within a configured time period (for example, within a 30-day timeframe), predicts that a new item may have the same trend, and displays the predicted item in recommendations.
```

2023-01-16 10:38 UTC, DominikaK commented on docs/personalization/recommendation_models.md
> +Recognizes purchase patterns and returns recommendations for items where these pattern can occur.
```suggestion
A recurring purchase model recognizes purchase patterns and returns recommendations for items where these patterns can occur.
```

2023-01-16 10:38 UTC, DominikaK commented on docs/personalization/recommendation_models.md
> +Model recommends items which are suitable for this pattern. Item recommendations are displayed 20% before the estimated pattern of repeating purchasing the product.
```suggestion
The model recommends items which are suitable for this pattern. Item recommendations are displayed 20% before the estimated pattern of repeating purchasing the product.
```
"are displayed 20% before" - that's somehow awkward, even with the explanation below

2023-01-16 10:38 UTC, DominikaK commented on docs/personalization/recommendation_models.md
> +It means, for example, if the pattern covers 100 days, when the optimal time comes from the day 80. the recommendation begins to display. When user purchases the recommended item on the day 92.,
```suggestion
It means, for example, that if the pattern covers 100 days, when the optimal time comes from day 80., the recommendation begins to display. When a user purchases the recommended item on day 92., 
```

2023-01-16 10:38 UTC, DominikaK commented on docs/personalization/recommendation_models.md
> +the recommendation is no longer showed and the counter resets.
```suggestion
the recommendation is no longer shown and the counter resets.
```

2023-01-16 10:38 UTC, DominikaK commented on docs/personalization/recommendation_models.md
> +    Minimum time period for this model is 4 days, but the model works better if you set longer time period.
```suggestion
    Minimum time period for this model is 4 days, but the model works better if you set a longer time period.
    
```

2023-01-16 10:58 UTC, juskora commented on docs/personalization/recommendation_models.md
> +The model recommends items which are suitable for this pattern. Item recommendations are displayed 20% before the estimated pattern of repeating purchasing the product.
```suggestion
The model recommends items which are suitable for this pattern. Item recommendations are displayed 20% before the completion of estimated pattern of repeating purchasing the product.
```

2023-01-16 11:54 UTC, DominikaK approved these changes

2023-01-25 10:28 UTC, merged