IBX-3773: Added taxonomy entry assignment note
ezsystems/user-documentation pull request #180
Opened 2023-01-18 14:18 UTC by juskora

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | https://issues.ibexa.co/browse/IBX-3773
| Versions      | master, 4.3

#### Checklist

- [x] Text renders correctly
- [x] Text has been checked with vale
- [ ] Description metadata is up to date
- [ ] Redirects cover removed/moved pages
- [ ] Added link to this PR in relevant JIRA ticket or code PR

2023-01-23 07:03 UTC, DominikaK requested changes

2023-01-23 07:03 UTC, DominikaK commented on docs/content_management/taxonomy/work_with_tags.md
> +!!!note
```suggestion
!!! note
```

2023-01-23 07:03 UTC, DominikaK commented on docs/content_management/taxonomy/work_with_tags.md
> +    Because tags are assigned per Content, not per Field, you cannot use two the same Fields for
```suggestion
    Because tags are assigned per content, not per Field, you cannot use two Fields for
```

2023-01-25 07:12 UTC, DominikaK approved these changes

2023-01-25 07:13 UTC, webhdx approved these changes

2023-01-25 10:21 UTC, merged