IBX-5948: Product page URLs
ezsystems/user-documentation pull request #205
Opened 2023-06-21 13:17 UTC by julitafalcondusza

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | https://issues.ibexa.co/browse/IBX-5948
| Versions      | master
| Edition       | Content

Product Page URLs added in PIM.

#### Checklist

- [x] Text renders correctly
- [x] Text has been checked with vale
- [x] Description metadata is up to date
- [x] Redirects cover removed/moved pages
- [x] Added link to this PR in relevant JIRA ticket or code PR

2023-06-21 15:21 UTC, SylvainGuittard commented on docs/pim/work_with_product_page_urls.md
> +It improves the user experience and reduces bounce rates on the website.
I think this part can be moved at the top of the page

2023-06-30 13:00 UTC, julitafalcondusza commented on docs/pim/work_with_product_page_urls.md
> +Product can have multiple URLs if it is included in many catalogs and exposed to many sites.
As discussed with @kisztof - sentence deleted.

2023-07-04 21:41 UTC, SylvainGuittard commented on docs/pim/work_with_product_page_urls.md
> +Products have their own [attributes](products.md#attributes) that provide different information about them.
```suggestion
Products have their own [attributes](products.md#attributes) to define product specifications. 
```

2023-07-04 21:42 UTC, SylvainGuittard commented on docs/pim/work_with_product_page_urls.md
> +!!! note
Not sure we want to keep this :)

2023-07-04 21:44 UTC, SylvainGuittard commented on docs/pim/work_with_product_page_urls.md
> +| Selection | Selected value with configured separator | children-infants |
```suggestion
| Type | Returned value | Example|
|---|---|---|
| Checkbox | Label of the checkbox is checked | wireless |
| Color | Hex code value | 8b0000 |
| Integer | Integer | 26 |
| Selection | Selected value with configured separator | children-infants |
| Measurement (single) | Single value and unit | 256gb |
| Measurement (range) | Value unit and minimum/maximum values | 20-25cm|
```
Changed the order so it's consistent with the list above

2023-07-04 21:47 UTC, SylvainGuittard reviewed
Few changes to make it perfect :)

2023-07-04 21:47 UTC, SylvainGuittard commented on docs/pim/work_with_product_page_urls.md
> +Having keyword-rich URLs also improves the product's visibility in search engine results and boost the page's ranking in search results.
```suggestion
Having keyword-rich URLs also improves the product's visibility in search engine results and boosts the page's ranking in search results.
```

2023-07-05 08:47 UTC, SylvainGuittard approved these changes

2023-07-05 08:52 UTC, MagdalenaZuba requested changes

2023-07-05 08:52 UTC, MagdalenaZuba commented on docs/pim/work_with_product_page_urls.md
> +Every [Product item](products.md) has a system URL that is automatically generated. It is based on a pattern that combines fields and attributes to build the URL (URL alias name pattern).
```suggestion
Every [product item](products.md) has a system URL that is automatically generated. 
It is based on a pattern that combines fields and attributes to build the URL (URL alias name pattern).
```

2023-07-05 08:52 UTC, MagdalenaZuba commented on docs/pim/work_with_product_page_urls.md
> +To do it, fill in all necessary information and choose the attributes that you want to use in URL alias name pattern field and click **Save** button.
```suggestion
To do it, fill in all the necessary information and choose the attributes that you want to use in URL alias name pattern field and click **Save** button.
```

2023-07-05 08:52 UTC, MagdalenaZuba commented on docs/pim/work_with_product_page_urls.md
> +Customized URLs are easy to remember, help for SEO optimatization and reduce bounce rates on the website.
```suggestion
Customized URLs are easy to remember, help with SEO optimization and reduce bounce rates on the website.
```

2023-07-05 08:52 UTC, MagdalenaZuba commented on docs/pim/work_with_product_page_urls.md
> +Now, in the **URL** tab in the product's view, you can see new custom URL for the Product.
```suggestion
Now, in the **URL** tab in the product's view, you can see new custom URL for the product.
```

2023-07-05 08:52 UTC, MagdalenaZuba commented on docs/pim/work_with_product_page_urls.md
> +2\. Choose the Product from the list.
```suggestion
2\. Choose a product from the list.
```

2023-07-05 08:52 UTC, MagdalenaZuba commented on docs/pim/work_with_product_page_urls.md
> +You can create custom URL for each Product.
```suggestion
You can create custom URL for each product.
```

2023-07-05 08:52 UTC, MagdalenaZuba commented on docs/pim/work_with_product_page_urls.md
> +When you are creating new [Product Type](create_product_types.md) you can set up Product URL alias name pattern.
```suggestion
When you are creating new [Product Type](create_product_types.md) you can set up product URL alias name pattern.
```

2023-07-05 11:09 UTC, MagdalenaZuba approved these changes

2023-07-10 08:47 UTC, merged