Add persona meta text
ezsystems/user-documentation pull request #220
Opened 2023-07-24 07:59 UTC by dabrt

| Question      | Answer |
| ------------- | --- |
| JIRA Ticket   | none |
| Versions      | all |
| Edition       | all |

Add meta text to main persona path articles, just in case they end up as being parts of a larger master page.

#### Checklist

- [x] Text renders correctly
- [x] Text has been checked with vale
- [x] Description metadata is up to date

2023-07-24 10:02 UTC, juskora requested changes

2023-07-24 10:30 UTC, dabrt commented on docs/persona_paths/shop_manager.md
> +description: Perform tasks related to running a virtual store.
```suggestion
description: Perform tasks related to running an electronic presence of your store.
```

2023-07-24 10:32 UTC, dabrt commented on docs/persona_paths/shop_manager.md
> +description: Perform tasks related to running a virtual store.
Fixed

2023-07-24 10:37 UTC, juskora commented on docs/persona_paths/administrator.md
> +description: Discover administrative tasks that you can perform in the back Office.
```suggestion
description: Discover administrative tasks that you can perform in the Back Office.
```

2023-07-24 10:37 UTC, juskora commented on docs/persona_paths/shop_manager.md
> +description: Perform tasks related to running an electronic presence of your store.
How about sth with "online store"?

2023-07-24 10:37 UTC, juskora commented on docs/persona_paths/shop_manager.md
>  # Shop manager role
It shouldn't be Store manager according to the discussion about the landing page tiles in the user-doc?

2023-07-24 11:20 UTC, juskora requested changes

2023-07-24 11:20 UTC, juskora commented on docs/persona_paths/shop_manager.md
> +description: Perform tasks related to running an electronic presence of your store.
This must be changed. Electronic presence is not a proper wording here.

2023-07-24 12:08 UTC, juskora approved these changes

2023-07-24 14:46 UTC, adriendupuis commented on docs/persona_paths/organize_content.md
> +description: Organize the content of your website by copying or moving Content items, controlling Locations and URLs and classifying content.
```suggestion
description: Organize the content of your website by copying or moving Content items, controlling Locations and URLs, and classifying content.
```

2023-07-25 07:03 UTC, MagdalenaZuba approved these changes

2023-07-25 07:44 UTC, merged