IBX-6264: Clarify what hidden state is
ezsystems/user-documentation pull request #224
Opened 2023-08-02 08:20 UTC by glye

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | https://issues.ibexa.co/browse/IBX-6264
| Versions      | all supported
| Edition       | all

Part of a multi-target goal to clarify what "hidden" state is, and warns about wrong usage.

See also:
https://github.com/ezsystems/developer-documentation/pull/2091
https://github.com/ezsystems/developer-documentation/pull/2092

#### Checklist

- [ ] Text renders correctly
- [ ] Text has been checked with vale
- [x] Description metadata is up to date
- [ ] Redirects cover removed/moved pages
- [x] Added link to this PR in relevant JIRA ticket or code PR

2023-08-02 08:25 UTC, glye commented
D'oh, links are across repos. Fixing...

2023-08-03 07:52 UTC, dabrt commented on docs/content_management/content_organization/copy_move_hide_content.md
> +A hidden Content item is not shown in the frontend when using the default templates. It is also grayed out in the Content Tree.
If it is not shown with the default templates, what is the special case when it can still be shown? Not retrieved with API but shown?

2023-08-03 08:09 UTC, dabrt requested changes

2023-08-03 08:09 UTC, dabrt commented on docs/content_management/content_organization/copy_move_hide_content.md
> +    or [**Object State**](https://doc.ibexa.co/en/latest/administration/content_organization/object_states/),
```suggestion
    or [**Object State**](https://doc.ibexa.co/projects/userguide/en/latest/content_management/content_organization/classify_content/#object-states),
```

2023-08-03 08:09 UTC, dabrt commented on docs/content_management/content_organization/copy_move_hide_content.md
> +    Or use other permission-based [**Limitations**](https://doc.ibexa.co/en/latest/permissions/limitations/).
```suggestion
    Or use other permission-based [**Limitations**](https://doc.ibexa.co/projects/userguide/en/latest/permission_management/work_with_permissions/).
```

2023-08-03 08:14 UTC, glye commented on docs/content_management/content_organization/copy_move_hide_content.md
> +    The visibility flag is a convenient feature for withdrawing content from the frontend. It acts as a simple filter in the default frontend templates.
Ah, that's what it's called :) 👍

2023-08-04 07:18 UTC, glye commented
TODO: Sync with changes in https://github.com/ezsystems/developer-documentation/pull/2091

2023-08-07 10:55 UTC, merged