EZP-31784 - Autosave description
ezsystems/user-documentation pull request #73
Opened 2020-10-09 11:34 UTC by dabrt

| Question      | Answer |
| ------------- | --- |
| JIRA Ticket   | EZP-31784 |
| Versions      | master |

A description of the Autosave feature

2020-10-09 11:57 UTC, DominikaK requested changes

2020-10-09 11:57 UTC, DominikaK commented on docs/publishing/publishing.md
> +eZ Platform comes with an Autosave feature that helps you preserve your work in an event of a failure while you edit a content item or product description.
What do you think about:
```suggestion
You work is saved automatically. Autosave helps you preserve your progress in an event of a failure while you edit a Content item or product.
```
This way avoids mentioning a feature, in the spirit of "don't describe features, describe what the user can do".
Although the passive could be fixed further...

2020-10-09 11:57 UTC, DominikaK commented on docs/publishing/publishing.md
> +product description.
```suggestion
To recover your work, open the most recent draft in the **Versions** tab of the Content item.
```
If product is stored in the content tree, it is a Content item, no need to mention it explicitly.

2020-10-09 11:57 UTC, DominikaK commented on docs/publishing/publishing.md
> +The feature is enabled by default, and set to save a draft of your work every 60 seconds.
```suggestion
Autosave is enabled by default, and set to save a draft of your work every 60 seconds.
```

2020-10-09 11:57 UTC, DominikaK commented on docs/publishing/publishing.md
> +You can toggle Autosave or change the time between saving attempts in **User settings**, by changing
```suggestion
You can toggle autosave or change the time between saving attempts in **User settings**, by changing
```

2020-10-09 11:57 UTC, DominikaK commented on docs/site_organization/working_with_page.md
> +        To help you preserve your work eZ Platform comes with an Autosave feature.
```suggestion
        To help you preserve your work eZ Platform autosaves your progress.
```

2020-10-09 11:57 UTC, DominikaK commented on docs/creating_content_basic.md
> +    To help you preserve your work eZ Platform comes with an Autosave feature.
```suggestion
    To help you preserve your work eZ Platform autosaves your progress.
```

2020-10-12 06:19 UTC, DominikaK approved these changes

2020-10-12 10:58 UTC, Nattfarinn approved these changes

2020-10-12 11:03 UTC, merged