EZP-32199 - SF documentation change
ezsystems/user-documentation pull request #89
Opened 2020-12-07 20:48 UTC by dabrt

| Question      | Answer |
| ------------- | --- |
| JIRA Ticket   | EZP-32199 |
| Versions      | master |

Add a note about SiteAccess matching priority.

2020-12-08 07:36 UTC, DominikaK requested changes

2020-12-08 07:36 UTC, DominikaK commented on docs/site_organization/site_factory.md
> +    A SiteAccess that you create in SiteFactory is always treated with lower priority than a SiteAccess
Indent missing in the whole note

2020-12-08 07:36 UTC, DominikaK commented on docs/site_organization/site_factory.md
> +    A SiteAccess that you create in SiteFactory is always treated with lower priority than a SiteAccess
```suggestion
    A SiteAccess that you create in Site Factory is always treated with lower priority than a SiteAccess 
```

2020-12-08 07:36 UTC, DominikaK commented on docs/site_organization/site_factory.md
> +    defined by the administrator as part of the [configuration procedure](https://doc.ibexa.co/en/latest/guide/siteaccess/#configuring-siteaccesses).
```suggestion
    defined by the administrator as part of [configuration](https://doc.ibexa.co/en/latest/guide/siteaccess/#configuring-siteaccesses). 
```

2020-12-08 07:36 UTC, DominikaK commented on docs/site_organization/site_factory.md
> +    For example, if you create a site that uses the `fr` path in SiteFactory, and the administrator
```suggestion
    For example, if you create a site that uses the `fr` path in Site Factory, and the administrator 
```

2020-12-08 12:31 UTC, DominikaK approved these changes

2020-12-17 12:02 UTC, mikadamczyk approved these changes

2020-12-17 13:43 UTC, merged